# Generated by Django 5.0.3 on 2024-03-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_preference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
