# Generated by Django 5.0.3 on 2024-04-30 03:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='Itinerary_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ItineraryItem',
        ),
    ]
