# Generated by Django 5.0.3 on 2024-04-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_planner', '0002_itinerary_itinerary_description_itinerary_is_private_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='Itinerary_description',
            new_name='itinerary_description',
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
