# Generated by Django 5.0.3 on 2024-04-30 12:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_planner', '0003_rename_itinerary_description_itinerary_itinerary_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'itinerary')},
        ),
    ]
